services:
  - type: web
    name: webmieow
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: dotnet WebMieow.dll
    dependsOn:
      - mysql-db
    envVars:
  - key: ConnectionStrings__DefaultConnection
    value: "server=turntable.proxy.rlwy.net;port=48832;database=railway;user=root;password=dzwizjmCOvrsOvBPyNQMIlFvVtcIitHQ;"



  - type: pserv
    name: mysql-db
    env: docker
    image: mysql:8.0
    plan: starter
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: Gtw3gpHa8cBAiGia
      - key: MYSQL_DATABASE
        value: webmieowdb
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
